import { defineConfig } from 'vite';

export default defineConfig({
  server: {
    watch: {
      // This is to avoid Vite from processing HTML files generated by the WTR coverage report.
      ignored: ['**/.coverage/**'],
    },
  },
});
